#!/bin/bash
export PATH=/bin:/sbin:/usr/bin:/usr/sbin:/usr/local/bin:/usr/local/sbin
LogPath="$PWD/"
Log="createproj.log"
Msg=""

function Report
{
	echo -e "[`date +\"%F %H:%M:%S\"`] $1" | tee -a ${LogPath}${Log}
	if [ $# -eq 2 ]
	then
		exit 1
	fi
}

function ReportInfo
{
	Report "[INFO] $1"
}

function ReportWarn
{
	Report "[WARNING] $1" 1
}

if [ $# -lt 1 ]
then
	ReportWarn "没有需要打包的项目"
fi

for i in `echo $@`
do
	if [ -d $i ]
	then
		Msg="重建$i： "
	else
		mkdir $i
		Msg="新建$i： "
	fi
	if [ -s $i/BUILDSN ]
	then
		Msg=${Msg}"保留BUILDSN "
	else
		echo 0 > $i/BUILDSN
		Msg=${Msg}"新建BUILDSN 0 "
	fi
	if [ -s $i/VISION ]
	then
		Msg=${Msg}"保留VISION "
	else
		echo 0.1 > $i/VISION
		Msg=${Msg}"新建VISION 0.1 "
	fi
	if [ -d $i/src ]
	then
		rm -rf $i/src
		Msg=${Msg}"清空$i/src "
	else
		Msg=${Msg}"新建$i/src "
	fi
	mkdir -p $i/src
	if [ ! -s $i/$i.spec ]
	then
		scp sample.spec $i/$i.spec
		Msg=${Msg}"复制$i.spec "
	fi
	ReportInfo "${Msg}"
	Msg=""
done	
