#!/bin/bash
export PATH=/bin:/sbin:/usr/bin:/usr/sbin:/usr/local/bin:/usr/local/sbin
LogPath="$PWD/"
Log="createproj.log"
Msg=""

function Report
{
	echo -e "[`date +\"%F %H:%M:%S\"`] $1" | tee -a ${LogPath}${Log}
	if [ $# -eq 2 ]
	then
		exit 1
	fi
}

function ReportInfo
{
	Report "[INFO] $1"
}

function ReportWarn
{
	Report "[WARNING] $1" 1
}

if [ $# -lt 1 ]
then
	ReportWarn "Not find the package to build."
fi

for i in `echo $@`
do
	if [ -d $i ]
	then
		Msg="rebuild $i£º "
	else
		mkdir $i
		Msg="mkdir $i : "
	fi
	if [ -s $i/BUILDSN ]
	then
		Msg=${Msg}"reuse BUILDSN "
	else
		echo 0 > $i/BUILDSN
		Msg=${Msg}"new BUILDSN 0 "
	fi
	if [ -s $i/VISION ]
	then
		Msg=${Msg}"reuse VISION "
	else
		echo 0.1 > $i/VISION
		Msg=${Msg}"new VISION 0.1 "
	fi
	if [ -d $i/src ]
	then
		rm -rf $i/src
		Msg=${Msg}"rm $i/src "
	else
		Msg=${Msg}"new $i/src "
	fi
	mkdir -p $i/src
	if [ ! -s $i/$i.spec ]
	then
		scp sample.spec $i/$i.spec
		Msg=${Msg}"copy $i.spec "
	fi
	ReportInfo "${Msg}"
	Msg=""
done	
